import { Alert, StyleSheet, View } from 'react-native';
import { useRouter } from 'expo-router';
import * as LocalAuthentication from 'expo-local-authentication';
import { ParentHeader, ScreenContainer, SectionLabel, SettingsGroup, SettingsRow, Txt } from '@/components';
import { useAppStore } from '@/stores/appStore';
import { useLockStore } from '@/stores/lockStore';

export default function Safety(){const router=useRouter();const p=useAppStore(s=>s.childProfiles.find(x=>x.id===s.activeChildProfileId)??s.childProfiles[0]??null);const biometric=useLockStore(s=>s.biometricEnabled);const setBio=async(next:boolean)=>{if(next&&!(await LocalAuthentication.isEnrolledAsync()))return Alert.alert('Face ID unavailable','Set up Face ID or fingerprint in system settings first.');useLockStore.getState().setBiometricEnabled(next)};return <ScreenContainer scroll style={styles.root}><ParentHeader title="PIN & safety" onBack={()=>router.back()}/><SectionLabel>What’s protected right now</SectionLabel><View style={styles.facts}><Txt size={14} lineHeight={21}>⏰ {p?.nickname ?? 'Your child'}’s limit is <Txt weight="black" size={14}>{p?.dailyLimitMinutes ?? 45} min a day</Txt>. When it’s up, videos pause until you enter the PIN.</Txt><Txt size={14} lineHeight={21}>🚪 {p?.nickname ?? 'Your child'} <Txt weight="black" size={14}>can’t leave Child Mode</Txt> or open settings without the PIN.</Txt><Txt size={14} lineHeight={21}>▶ Only videos <Txt weight="black" size={14}>you approved</Txt> can ever play.</Txt></View><SectionLabel>Controls</SectionLabel><SettingsGroup><SettingsRow icon="🔢" iconBg="#FFDAD3" title="Change PIN" value="•••• ›" onPress={()=>router.push('/(parent)/change-pin')}/><SettingsRow icon="◉" iconBg="#CDEDF4" title="Face ID unlock" toggle={{value:biometric,onChange:setBio}}/><SettingsRow icon="✉" iconBg="#EDE7DA" title="Reset PIN by email" chevron onPress={()=>Alert.alert('Reset email','We’ll send a secure reset link to your account email.')}/></SettingsGroup></ScreenContainer>}
const styles=StyleSheet.create({root:{paddingTop:16,gap:16},facts:{backgroundColor:'#fff',borderRadius:20,padding:16,gap:14}});
