import type { ReactNode } from 'react';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { formatDailyLimit } from '@littleloop/shared';
import { colors, radii, shadows } from '@/theme/tokens';
import { ChildAvatar } from './ChildAvatar';
import { AppIcon } from './AppIcon';
import { Txt } from './Txt';

/**
 * Horizontal child chips. `onEdit` puts a pencil on the selected chip — the
 * streaming-app convention (Netflix/Disney+/Paramount+) and the only visible route
 * into renaming a child or changing their avatar.
 */
export function ChildSwitcher({ profiles, activeId, onSelect, onAdd, onEdit }: { profiles: { id: string; nickname: string; avatar: any }[]; activeId: string | null; onSelect: (id: string) => void; onAdd?: () => void; onEdit?: (id: string) => void }) {
  return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.switcher}>{profiles.map((p) => {
    const active = p.id === activeId;
    return <Pressable key={p.id} accessibilityRole="button" accessibilityState={{ selected: active }} accessibilityLabel={`Show settings for ${p.nickname}`} onPress={() => onSelect(p.id)} style={[styles.chip, active && styles.chipActive]}>
      <ChildAvatar avatar={p.avatar} size={22} />
      <Txt weight="extrabold" size={13} color={active ? '#fff' : colors.parent.muted}>{p.nickname}</Txt>
      {active && onEdit ? <Pressable accessibilityRole="button" accessibilityLabel={`Edit ${p.nickname}’s profile`} onPress={() => onEdit(p.id)} hitSlop={10} style={styles.editBadge}><Txt weight="black" size={9} color="#fff">EDIT</Txt></Pressable> : null}
    </Pressable>;
  })}{onAdd ? <Pressable accessibilityRole="button" accessibilityLabel="Add child" onPress={onAdd} style={styles.addChip}><Txt weight="extrabold" size={18} color={colors.child.skyDeep}>＋</Txt></Pressable> : null}</ScrollView>;
}
export function IdentityCard({ name = 'Parent', email, onPress }: { name?: string; email?: string; onPress?: () => void }) { return <Pressable accessibilityRole={onPress ? 'button' : undefined} onPress={onPress} disabled={!onPress} style={styles.identity}><View style={styles.identityAvatar}><Txt weight="black" size={15} color="#fff">{name[0]?.toUpperCase()}</Txt></View><View style={styles.identityText}><Txt weight="bold" size={16} numberOfLines={1}>{name}</Txt><Txt size={12} color={colors.parent.muted} numberOfLines={1}>{email ?? 'Parent account'}</Txt></View>{onPress ? <Txt size={22} color={colors.parent.muted}>›</Txt> : null}</Pressable>; }
export function PremiumBanner({ onPress }: { onPress: () => void }) { return <Pressable onPress={onPress} style={shadows.card}><LinearGradient colors={[colors.child.sun, '#FFAF3E']} start={{x:0,y:0}} end={{x:1,y:1}} style={styles.premium}><AppIcon name="premium" size={38} /><View style={{ flex: 1 }}><Txt weight="black" size={15} color={colors.parent.night}>Upgrade to Premium</Txt><Txt size={12} color="#6C5312">Caregiver sharing, search, and more</Txt></View><Txt size={22} color={colors.parent.night}>›</Txt></LinearGradient></Pressable>; }
export function OwlBubble({ children }: { children: ReactNode }) { return <View style={styles.owlRow}><ChildAvatar avatar="bear" size={44} /><View style={styles.bubble}><Txt weight="bold" size={14} color={colors.parent.night}>{children}</Txt></View></View>; }
export function OptionList({ options, selected, onSelect }: { options: { value: number; nickname: string }[]; selected: number | null; onSelect: (v: number) => void }) { return <View style={styles.options}>{options.map(o => <Pressable key={o.value} accessibilityRole="button" accessibilityState={{ selected: o.value === selected }} onPress={() => onSelect(o.value)} style={[styles.option, o.value === selected && styles.optionSelected]}><Txt weight="black" size={16}>{formatDailyLimit(o.value)}</Txt><Txt size={13} color={colors.parent.muted} style={{flex:1}}>{o.nickname}</Txt>{o.value === selected ? <Txt weight="black" color={colors.child.skyDeep}>✓</Txt> : null}</Pressable>)}</View>; }
export function WeekBars({ values }: { values: number[] }) { const max = Math.max(...values, 1); return <View style={styles.bars}>{values.slice(-7).map((v, i) => <View key={i} style={[styles.bar, { height: 18 + (v / max) * 58, backgroundColor: i === 6 ? colors.child.coral : v / max > .6 ? colors.child.skyDeep : '#E4DCCF' }]} />)}</View>; }
export function StatusBadge({ state = 'LIVE' }: { state?: 'LIVE' | 'REVIEW' }) { const c = state === 'LIVE' ? colors.state.live : colors.state.review; return <View style={[styles.badge, { backgroundColor: c.bg }]}><Txt weight="black" size={10} color={c.text}>{state === 'LIVE' ? 'Approved' : 'Needs review'}</Txt></View>; }
const styles = StyleSheet.create({ switcher:{gap:8},chip:{height:38,borderRadius:19,backgroundColor:'#fff',paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:5},chipActive:{backgroundColor:colors.parent.night},editBadge:{minWidth:34,height:22,borderRadius:11,marginLeft:2,marginRight:-4,paddingHorizontal:5,backgroundColor:'rgba(255,255,255,.22)',alignItems:'center',justifyContent:'center'},addChip:{height:38,width:38,borderRadius:19,borderWidth:1.5,borderStyle:'dashed',borderColor:colors.child.skyDeep,alignItems:'center',justifyContent:'center'},identity:{backgroundColor:'#fff',borderRadius:radii.card,padding:16,flexDirection:'row',alignItems:'center',gap:12,...shadows.card},identityAvatar:{width:34,height:34,borderRadius:17,backgroundColor:colors.parent.night,alignItems:'center',justifyContent:'center'},identityText:{flex:1,minWidth:0,gap:2},premium:{borderRadius:radii.card,padding:16,flexDirection:'row',alignItems:'center',gap:10},owlRow:{flexDirection:'row',alignItems:'center',gap:8},bubble:{backgroundColor:'#fff',padding:14,borderRadius:12,flex:1,...shadows.card},options:{backgroundColor:'#fff',borderRadius:radii.card,overflow:'hidden',...shadows.card},option:{minHeight:55,paddingHorizontal:16,flexDirection:'row',alignItems:'center',gap:8,borderBottomWidth:1,borderBottomColor:colors.parent.hairline},optionSelected:{backgroundColor:'#EAF6FA',borderLeftWidth:3,borderLeftColor:colors.child.skyDeep},bars:{height:82,flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',gap:8,paddingHorizontal:4},bar:{flex:1,borderTopLeftRadius:5,borderTopRightRadius:5},badge:{borderRadius:10,paddingVertical:3,paddingHorizontal:7} });
